### ISSUE TITLE
(제안) 사용자 등록의 GitHub ID 입력 칸 HelperText

### ISSUE THREAD

**Issue by codeisneverodd** [kimseo-0/Dcom-Daily-Commit-Frontend#11]
## 제안이유
GitHub ID 칸에 올바르지 않은 아이디를 적고 되지 않는다고 문의하는 유저가 생김.
향후 유저가 많아지고 문의가 늘어날 경우 아래의 예상이유를 반복적으로 설명해주어야함.
## 예상 이유
1. GitHub 상의 이름과 아이디를 헷갈려서
2. 대소문자 구분을 하지 않아서
3. 이메일을 적어서
## 제안
GitHub ID의 HelperText로 
'github.com/아이디'의 아이디를 입력해주세요
를 추가.

**Comment by kimseo-0** [comment]
## 수정 제안
제안 : '본인의 github 프로필 URL 속 ID를 입력해주세요. ex) URL : github.com/kimseo-0 → ID : kiseo-0'
