### ISSUE TITLE
RULES 수정 사항

### ISSUE THREAD

**Issue by codeisneverodd** [kimseo-0/Dcom-Daily-Commit-Frontend#5]
RULES의 내용을 아래와 같이 수정

1. 개인 계정에 1일 1커밋을 목표로 합니다.
2. 개인 프로젝트/알고리즘/블로깅 등 어떤 커밋이든지 상관 없습니다.
3. 커밋은 절대 강요하거나 눈치주지 않습니다. 오직 벌금만 강요합니다!
4. 매주 일요일마다 집계 (일-토 기준), 커밋 한번 빠졌을 때마다 벌금 1000원 입니다.
5. 랭킹은 (연속 커밋일 * 10 + 총 커밋 * 5 - 남은 벌금 / 50)의 계산식으로 정해집니다.
6. Private Repository에 커밋했다면 Contribution Setting을 바꾸어 주어야 본 페이지에 반영됩니다.

**Comment by kimseo-0** [comment]
수정완료
