### ISSUE TITLE
사용자 등록시 Name에 validation 추가

### ISSUE THREAD

**Issue by codeisneverodd** [kimseo-0/Dcom-Daily-Commit-Frontend#6]
1. Name을 입력받을 때, 2자리-4자리 한글이름으로 validation 추가
2. helperText로  '실명을 적어주세요' 또는 '2자리-4자리의 한글이름을 입력해주세요' 추가.

**Comment by codeisneverodd** [comment]
helperText내용은 바꿔도 무방

**Comment by kimseo-0** [comment]
1. 1자리-5자리로
2. 한글 실명(1~5자리)을 입력해주세요.

**Comment by codeisneverodd** [comment]
확인했습니당
