### ISSUE TITLE
오늘 '0-9시 사이의 커밋 내용은 어제의 커밋으로' 집계된다는 내용 추가 필요

### ISSUE THREAD

**Issue by codeisneverodd** [kimseo-0/Dcom-Daily-Commit-Frontend#8]
크롤링 시간대 문제로 +9시간 차이가 생겨 0-9시의 커밋 내용은 커밋한 날짜로 적용되지 않고, 그 전날로 집계된다는 것을 알려주는 내용을 포함하여야함. 
이것을 사용자에게 크롤링 이슈로 표기하지 않고, 규칙에 하루의 기준은 '오늘 09:01-다음날 09:00 입니다'와 같은 형식으로 적어서, 크롤링 문제 때문이 아닌 우리가 규칙을 이렇게 정한 것이다 라고 표기하는 것도 좋을 것 같음.

**Comment by kimseo-0** [comment]
" 오늘 09:01-다음날 09:00 입니다. " 로 표시하면 좋을 것같습니다. 해당 내용 적용하겠습니다.
